import SwiftUI

/// A single anchored mark over rendered document text. Highlight, annotation, and
/// comment-thread (issues #1/#2/#3) are all this one entity — they differ only in
/// how many `comments` it has: `[]` is a highlight, one is an annotation (#2),
/// more than one (with `resolved` toggled) is a comment thread (#3).
struct Mark: Codable, Identifiable, Equatable {
    let id: UUID
    var anchor: TextAnchor
    var color: HighlightColor
    var comments: [Comment]
    var resolved: Bool
    let createdAt: Date
    var updatedAt: Date

    init(id: UUID = UUID(), anchor: TextAnchor, color: HighlightColor,
         comments: [Comment] = [], resolved: Bool = false,
         createdAt: Date = Date(), updatedAt: Date = Date()) {
        self.id = id
        self.anchor = anchor
        self.color = color
        self.comments = comments
        self.resolved = resolved
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }
}

struct Comment: Codable, Identifiable, Equatable {
    let id: UUID
    var author: String
    var text: String
    let createdAt: Date
    var editedAt: Date?

    init(id: UUID = UUID(), author: String, text: String, createdAt: Date = Date(), editedAt: Date? = nil) {
        self.id = id
        self.author = author
        self.text = text
        self.createdAt = createdAt
        self.editedAt = editedAt
    }
}

enum HighlightColor: String, Codable, CaseIterable, Equatable {
    case yellow, green, blue, pink, purple

    var swiftUIColor: Color {
        switch self {
        case .yellow: return Color(red: 0.98, green: 0.85, blue: 0.24)
        case .green: return Color(red: 0.49, green: 0.83, blue: 0.44)
        case .blue: return Color(red: 0.40, green: 0.69, blue: 0.98)
        case .pink: return Color(red: 0.94, green: 0.50, blue: 0.70)
        case .purple: return Color(red: 0.68, green: 0.51, blue: 0.94)
        }
    }
}

/// Robust anchor over the *rendered* text (what the user selects), not DOM offsets —
/// the HTML is regenerated by marked on every reload. Modeled on the W3C
/// TextQuoteSelector; resolved in bridge.js after each render.
struct TextAnchor: Codable, Equatable {
    var quote: String
    var prefix: String
    var suffix: String
    var startOffset: Int
}

/// One JSON file per viewed document, in Application Support.
struct MarkDocument: Codable {
    var schemaVersion: Int
    var filePath: String
    var contentHash: String
    var marks: [Mark]
}
